version: "3"
services:
  db:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    ports:
        - "5432:5432"
    network_mode: "host"

  osm_downloader:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db

