version: "3"
services:
  db:
    image: postgis/postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    ports:
        - "5432:5432"

  osm_downloader:
    build: ..
    volumes:
      - .:/app
    depends_on:
      - db

