import datetime
from sqlmodel import Field, SQLModel


class SummaryActivity(SQLModel, table=True):
    athlete_id: int = Field(default=None, nullable=True)
    name: str = Field(default=None, nullable=True)
    distance: float = Field(default=None, nullable=True)
    moving_time: int = Field(default=None, nullable=True)
    elapsed_time: int = Field(default=None, nullable=True)
    total_elevation_gain: float = Field(default=None, nullable=True)
    type: str = Field(default=None, nullable=True)
    sport_type: str = Field(default=None, nullable=True)
    workout_type: int = Field(default=None, nullable=True)
    id = Field(int, primary_key=True)
    external_id: str = Field(default=None, nullable=True)
    upload_id: int = Field(default=None, nullable=True)
    start_date: datetime.datetime = Field(default=None, nullable=True)
    start_date_local: datetime.datetime = Field(default=None, nullable=True)
    timezone: str = Field(default=None, nullable=True)
    utc_offset: int = Field(default=None, nullable=True)
    start_latlng: str = Field(default=None, nullable=True)
    end_latlng: str = Field(default=None, nullable=True)
    location_city: str = Field(default=None, nullable=True)
    location_state: str = Field(default=None, nullable=True)
    location_country: str = Field(default=None, nullable=True)
    achievement_count: int = Field(default=None, nullable=True)
    kudos_count: int = Field(default=None, nullable=True)
    comment_count: int = Field(default=None, nullable=True)
    athlete_count: int = Field(default=None, nullable=True)
    photo_count: int = Field(default=None, nullable=True)
    map_id: str = Field(default=None, nullable=True)
    trainer: bool = Field(default=None, nullable=True)
    commute: bool = Field(default=None, nullable=True)
    manual: bool = Field(default=None, nullable=True)
    private: bool = Field(default=None, nullable=True)
    flagged: bool = Field(default=None, nullable=True)
    gear_id: str = Field(default=None, nullable=True)
    from_accepted_tag: bool = Field(default=None, nullable=True)
    average_speed: float = Field(default=None, nullable=True)
    max_speed: float = Field(default=None, nullable=True)
    average_cadence: float = Field(default=None, nullable=True)
    average_watts: float = Field(default=None, nullable=True)
    weighted_average_watts: float = Field(default=None, nullable=True)
    kilojoules: float = Field(default=None, nullable=True)
    device_watts: bool = Field(default=None, nullable=True)
    has_heartrate: bool = Field(default=None, nullable=True)
    average_heartrate: float = Field(default=None, nullable=True)
    max_heartrate: float = Field(default=None, nullable=True)
    max_watts: int = Field(default=None, nullable=True)
    pr_count: int = Field(default=None, nullable=True)
    total_photo_count: int = Field(default=None, nullable=True)
    has_kudoed: bool = Field(default=None, nullable=True)
    suffer_score: int = Field(default=None, nullable=True)
