version: "3.8"
services:
  db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./database/init_db/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - ./database/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
