CREATE TABLE IF NOT EXISTS strava_athlete
(
    id serial primary key not null,
    username varchar,
    resource_state int,
    firstname varchar,
    lastname varchar,
    bio varchar,
    city varchar,
    state varchar,
    country varchar,
    sex varchar,
    premium bool,
    summit bool,
    created_at timestamptz,
    updated_at timestamptz,
    badge_type_id integer,
    weight double precision,
    profile_medium varchar,
    profile varchar,
    friend varchar,
    follower varchar
);
CREATE TABLE IF NOT EXISTS strava_tokens(
    access_token varchar not null primary key,
    refresh_token varchar,
    expires_at int,
    expires_in int,
    athlete_id bigint not null REFERENCES strava_athlete(id),
    token_type varchar
);
CREATE TABLE IF NOT EXISTS strava_activities(
    id bigint not null primary key,
    external_id varchar,
    upload_id bigint,
    athlete int REFERENCES strava_athlete(id),
    name varchar,
    distance double precision,
    moving_time int,
    elapsed_time int,
    total_elevation_gain double precision,
    elev_high double precision,
    elev_low double precision,
    type varchar,
    sport_type varchar,
    start_date timestamptz,
    start_date_local timestamptz,
    timezone varchar,
    start_latlng varchar,
    end_latlng varchar,
    achievement_count int,
    kudos_count int,
    comment_count int,
    athlete_count int,
    photo_count int,
    map varchar,
    trainer bool,
    commute bool,
    manual bool,
    private bool,
    flagged bool,
    workout_type int,
    average_speed double precision,
    max_speed double precision,
    has_kudoed bool,
    hide_from_home bool,
    gear_id varchar,
    kilojoules double precision,
    average_watts double precision,
    device_watts bool,
    max_watts int,
    weighted_average_watts int
);
